# Use a lightweight Python image
FROM python:3.11

# Install pyenv dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    python-openssl \
    libgdbm-dev \
    libnss3-dev \
    libdb5.3-dev \
    libgdbm-compat-dev \
    libmpdec-dev \
    liblz4-dev


# Use ARG to receive environment variables from .env.dev
ARG PYENV_ROOT
ARG PATH

# Set up environment variables inside the container
ENV PYENV_ROOT=${PYENV_ROOT}
ENV PATH=${PATH}

# Install pyenv
RUN curl https://pyenv.run | bash

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# Install Python version with pyenv
RUN pyenv install 3.11.10
RUN pyenv global 3.11.10

# Set poetry to use pyenv's Python
RUN poetry env use $(pyenv which python)

# Copy the current directory into the container
COPY . /workspace
WORKDIR /workspace